export { default as catalogApp } from './app';
export { default as catalogRoutes } from './routes';

export type { HomePromoVideoButtonSlotProps } from './slots/HomePromoVideoSlots/HomePromoVideoButtonSlot';
export type { HomePromoVideoModalSlotProps } from './slots/HomePromoVideoSlots/HomePromoVideoModalSlot';
export type { HomePromoVideoModalContentSlotProps } from './slots/HomePromoVideoSlots/HomePromoVideoModalContentSlot';
export type { HomeCourseCardSlotProps } from './slots/HomeCourseCardSlot';
export type { CourseAboutIntroSlotProps } from './slots/CourseAboutIntroSlot';
export type { CourseAboutCourseMediaSlotProps } from './slots/CourseAboutCourseMediaSlot';
export type { CourseAboutOverviewSlotProps } from './slots/CourseAboutOverviewSlot';
export type { CourseAboutSidebarSlotProps } from './slots/CourseAboutSidebarSlot';
export type { CourseAboutIntroVideoButtonSlotProps } from './slots/CourseAboutIntroVideoSlots/CourseAboutIntroVideoButtonSlot';
export type { CourseAboutIntroVideoModalSlotProps } from './slots/CourseAboutIntroVideoSlots/CourseAboutIntroVideoModalSlot';
export type { CourseAboutIntroVideoModalContentSlotProps } from './slots/CourseAboutIntroVideoSlots/CourseAboutIntroVideoModalContentSlot';
export type { CourseAboutSidebarSocialSlotProps } from './slots/CourseAboutSidebarSocialSlot';
export type { CourseAboutSidebarCoursePriceSlotProps } from './slots/CourseAboutSidebarCoursePriceSlot';
export type { CourseAboutCourseImageSlotProps } from './slots/CourseAboutCourseImageSlot';
export type { CourseAboutEnrollmentButtonSlotProps } from './slots/CourseAboutEnrollmentButtonSlot';
export type { CourseCatalogIntroSlotProps } from './slots/CourseCatalogIntroSlot';
export type { CourseCatalogSearchFieldSlotProps } from './slots/CourseCatalogSearchFieldSlot';
export type { CourseCatalogDataTableSlotProps } from './slots/CourseCatalogDataTableSlots/CourseCatalogDataTableSlot';
export type { CourseCatalogDataTableControlBarSlotProps } from './slots/CourseCatalogDataTableSlots/CourseCatalogDataTableControlBarSlot';
export type { CourseCatalogDataTableCardViewSlotProps } from './slots/CourseCatalogDataTableSlots/CourseCatalogDataTableCardViewSlot';
